config/routes.rb
Scorematch::Application.routes.draw do
  resources :matches

resources :golfers

resources :courses do
  resources :holes

end

 root 'courses#index'

  

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :holes
  has_many :matches

  validates :name, :par, :location, :presence => true
  validates :name, :uniqueness => true
end

app/models/golfer.rb
class Golfer < ActiveRecord::Base
  belongs_to :match

  validates :name, :handicap, :presence => true
  validates :name, :uniqueness => true
end

app/models/hole.rb
class Hole < ActiveRecord::Base
  belongs_to :course
  has_and_belongs_to_many :matches
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :course
  belongs_to :golfer
  has_many :holes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :par, :location, :tees, :slope, :rating)
    end
end

app/controllers/golfers_controller.rb
class GolfersController < ApplicationController
  before_action :set_golfer, only: [:show, :edit, :update, :destroy]

  # GET /golfers
  # GET /golfers.json
  def index
    @golfers = Golfer.all
  end

  # GET /golfers/1
  # GET /golfers/1.json
  def show
  end

  # GET /golfers/new
  def new
    @golfer = Golfer.new
  end

  # GET /golfers/1/edit
  def edit
  end

  # POST /golfers
  # POST /golfers.json
  def create
    @golfer = Golfer.new(golfer_params)

    respond_to do |format|
      if @golfer.save
        format.html { redirect_to @golfer, notice: 'Golfer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @golfer }
      else
        format.html { render action: 'new' }
        format.json { render json: @golfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /golfers/1
  # PATCH/PUT /golfers/1.json
  def update
    respond_to do |format|
      if @golfer.update(golfer_params)
        format.html { redirect_to @golfer, notice: 'Golfer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @golfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /golfers/1
  # DELETE /golfers/1.json
  def destroy
    @golfer.destroy
    respond_to do |format|
      format.html { redirect_to golfers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_golfer
      @golfer = Golfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def golfer_params
      params.require(:golfer).permit(:name, :handicap)
    end
end

app/controllers/holes_controller.rb
class HolesController < ApplicationController

 def create
 
# We need to get the course so that Rails knows where to assign the hole
@course = Course.find(params[:id])
 
# Here we create a new hole based on the course data from our form (params[:hole])
@hole = @course.holes.create(hole_params)
 
# Once the course is saved, we redirect the user back to the course they were viewing
redirect_to course_path(@course)
 
 end

# This needs to be at the bottom (it may be there, but you'll have to add your params)

# By default, Rails 4 does not trust input from the scary internet.
# You need to tell it what params (form fields, really) are acceptable
  def hole_params
    params.require(:hole).permit(:hole_number, :par, :handicap, :yardage)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render action: 'show', status: :created, location: @match }
      else
        format.html { render action: 'new' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:name, :golfer1_name, :golfer2_name, :course_name, :score, :winner, :course_id, :golfer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/golfers_helper.rb
module GolfersHelper
end

app/helpers/holes_helper.rb
module HolesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :par %><br>
    <%= f.number_field :par %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :tees %><br>
    <%= f.text_field :tees %>
  </div>
  <div class="field">
    <%= f.label :slope %><br>
    <%= f.number_field :slope %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<html lang="en">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Match Play Calc v1.0</title>
<link rel="stylesheet" href="..css/bootstrap.css" type="text/css">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="..css/bootstrap-responsive.css" rel="stylesheet">
</head>

<body>
<p />
<ul class="nav nav-tabs">
<li class="active"><a href="../courses">Courses</a></li>
<li><a href="../golfers">Golfers</a></li>
<li><a href="../matches">Matches</a></li>
</ul>

<section>

<h3>Courses</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Par</th>
      <th>Location</th>
      <th>Tees</th>
      <th>Slope</th>
      <th>Rating</th>
      <th>Holes</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.name, course %></td>
        <td><%= course.par %></td>
        <td><%= course.location %></td>
        <td><%= course.tees %></td>
        <td><%= course.slope %></td>
        <td><%= course.rating %></td>
	<td><%= course.holes.count %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %>
	| <%= link_to 'Destroy', course, method: :delete, date: {confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add Course', new_course_path, :class => 'btn btn-info btn-small' %>
<p />
</body>
</html>

app/views/courses/new.html.erb
<ul class="nav nav-tabs">
<li class="active"><a href="../courses">Courses</a></li>
<li><a href="../golfers">Golfers</a></li>
<li><a href="../matches">Matches</a></li>
</ul>

<h3>New Course</h3>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<html lang="en">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Match Play Calc v1.0</title>
<link rel="stylesheet" href="../layouts/bootstrap.css" type="text/css">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../layouts/bootstrap-responsive.css" rel="stylesheet">
</head>

<body>
<p />
<ul class="nav nav-tabs">
<li class="active"><a href="../courses">Courses</a></li>
<li><a href="../golfers">Golfers</a></li>
<li><a href="../matches">Matches</a></li>
</ul>

<section>
<p id="notice"><%= notice %></p>

<p>
  <h3> <%= @course.name %></h3>
</p>

<p>
  <strong>Par:</strong>
  <%= @course.par %>
</p>

<p>
  <strong>Location:</strong>
  <%= @course.location %>
</p>

<p>
  <strong>Tees:</strong>
  <%= @course.tees %>
</p>

<p>
  <strong>Slope:</strong>
  <%= @course.slope %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @course.rating %>
</p>
<!-- Hole Listing -->

<table border="1">

<tr><td>Hole #</td><% @course.holes.each do |c| %>
<td><strong><%= c.hole_number %><% end %></strong></td>
</tr><br>

<tr><td >Par</td><% @course.holes.each do |c| %>
<td><%= c.par %><% end %></td>
</tr><br>

<tr><td>Handicap</td><% @course.holes.each do |c| %>
<td><%= c.handicap %><% end %></td>
</tr><br>

<tr><td>Yardage</td><% @course.holes.each do |c| %>
<td><%= c.yardage %><% end %></td>
</tr><br>
</table>

<!-- New hole form -->
<h3>Add a hole:</h3>

<%= form_for([@course, @course.holes.build]) do |f| %>
<div class="field">
<%= f.label :hole_number %><br />
<%= f.text_field :hole_number %>
</div>
<div class="field">
<%= f.label :par %><br />
<%= f.text_field :par %>
</div>
<div class="field">
<%= f.label :handicap %><br />
<%= f.text_field :handicap %>
</div>
<div class="field">
<%= f.label :yardage %><br />
<%= f.text_field :yardage %>
</div>
<div class="actions">
<%= f.submit %>
</div>

<% end %>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>
</body>
</html>

app/views/golfers/_form.html.erb
<%= form_for(@golfer) do |f| %>
  <% if @golfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@golfer.errors.count, "error") %> prohibited this golfer from being saved:</h2>

      <ul>
      <% @golfer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :handicap %><br>
    <%= f.number_field :handicap %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/golfers/edit.html.erb
<h1>Editing golfer</h1>

<%= render 'form' %>

<%= link_to 'Show', @golfer %> |
<%= link_to 'Back', golfers_path %>

app/views/golfers/index.html.erb
<html lang="en">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Match Play Calc v1.0</title>
<link rel="stylesheet" href="..css/bootstrap.css" type="text/css">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="..css/bootstrap-responsive.css" rel="stylesheet">
</head>

<body>
<p />
<ul class="nav nav-tabs">
<li><a href="../courses">Courses</a></li>
<li class="active"><a href="../golfers">Golfers</a></li>
<li><a href="../matches">Matches</a></li>
</ul>

<section>
<h3>Golfers</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Handicap</th>
    </tr>
  </thead>

    <% @golfers.each do |golfer| %>
      <tr>
        <td><%= link_to golfer.name, golfer %></td>
        <td><%= golfer.handicap %></td>
        <td><%= link_to 'Edit', edit_golfer_path(golfer) %> | 
        <%= link_to 'Destroy', golfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Golfer', new_golfer_path, :class => 'btn btn-info btn-small' %>
<p />
</body>
</html>

app/views/golfers/new.html.erb
<ul class="nav nav-tabs">
<li><a href="../courses">Courses</a></li>
<li class="active"><a href="../golfers">Golfers</a></li>
<li><a href="../matches">Matches</a></li>
</ul>

<h3>New golfer</h3>

<%= render 'form' %>

<%= link_to 'Back', golfers_path %>

app/views/golfers/show.html.erb
<html lang="en">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Match Play Calc v1.0</title>
<link rel="stylesheet" href="..css/bootstrap.css" type="text/css">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="..css/bootstrap-responsive.css" rel="stylesheet">
</head>

<body>
<p />
<ul class="nav nav-tabs">
<li><a href="../courses">Courses</a></li>
<li class="active"><a href="../golfers">Golfers</a></li>
<li><a href="../matches">Matches</a></li>
</ul>

<section>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @golfer.name %>
</p>

<p>
  <strong>Handicap:</strong>
  <%= @golfer.handicap %>
</p>

<%= link_to 'Edit', edit_golfer_path(@golfer) %> |
<%= link_to 'Back', golfers_path %>
</section>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scorematch</title>
  <%= stylesheet_link_tag "application", "bootstrap", "bootstrap-responsive", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body width="100%">

<div class="container">
<div class="page-header"><h2>Match Play Calculator</h2></div>
<%= yield %>

</div>
</body>
</html>

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Match Name' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :golfer_1 %><br>
   <%= collection_select(:match, :golfer1_name, Golfer.all, :name, :name) %>  
  </div>
  <div class="field">
    <%= f.label :golfer_2 %><br>
   <%= collection_select(:match, :golfer2_name, Golfer.all, :name, :name) %>  
  </div>
  <div class="field">
    <%= f.label 'Course' %><br>
   <%= collection_select(:match, :course_id, Course.all, :id, :name) %>   
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :winner %><br>
    <%= f.text_field :winner %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h3>Edit Match</h3>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<html lang="en">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Match Play Calc v1.0</title>
<link rel="stylesheet" href="..css/bootstrap.css" type="text/css">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="..css/bootstrap-responsive.css" rel="stylesheet">
</head>

<body>
<p />
<ul class="nav nav-tabs">
<li><a href="../courses">Courses</a></li>
<li><a href="../golfers">Golfers</a></li>
<li class="active"><a href="../matches">Matches</a></li>
</ul>

<section>

<h3>Matches</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Golfer 1</th>
      <th>Golfer 2</th>
      <th>Course</th>
      <th>Score</th>
      <th>Winner</th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= link_to match.name, match %></td>
        <td><%= match.golfer1_name %></td>
        <td><%= match.golfer2_name %></td>
        <td><%= match.course.name %></td>
        <td><%= match.score %></td>
        <td><%= match.winner %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %>
        | <%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Match', new_match_path, :class => 'btn btn-info btn-small' %>
<p />
</body>
</html>

app/views/matches/new.html.erb
<ul class="nav nav-tabs">
<li><a href="../courses">Courses</a></li>
<li><a href="../golfers">Golfers</a></li>
<li class="active"><a href="../matches">Matches</a></li>
</ul>

<h3>New match</h3>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<html lang="en">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Match Play Calc v1.0</title>
<link rel="stylesheet" href="..css/bootstrap.css" type="text/css">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="..css/bootstrap-responsive.css" rel="stylesheet">
</head>

<body>
<p />
<ul class="nav nav-tabs">
<li><a href="../courses">Courses</a></li>
<li><a href="../golfers">Golfers</a></li>
<li class="active"><a href="../matches">Matches</a></li>
</ul>

<section>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @match.name %>
</p>

<p>
<strong><%= @match.golfer1_name %> </strong> vs. <strong><%= @match.golfer2_name %> -- (hcap here) <!-- want to add discreet handicap per golfer here %= @match.golfer2_name.handicap % --></strong> 
</p>

<p>
  <strong>Course:</strong>
  <%= @match.course.name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @match.score %>
</p>

<p>
  <strong>Winner:</strong>
  <%= @match.winner %>
</p>
<strong>Match Result:</strong>
<table border="1">

<tr><td>Hole #</td><% @match.course.holes.each do |c| %>
<td><strong><%= c.hole_number %><% end %></strong></td>
</tr><br>

<tr><td >Par</td><% @match.course.holes.each do |c| %>
<td><%= c.par %><% end %></td>
</tr><br>

<tr><td>Handicap</td><% @match.course.holes.each do |c| %>
<td><%= c.handicap %><% end %></td>
</tr><br>

<tr><td>Yardage</td><% @match.course.holes.each do |c| %>
<td><%= c.yardage %><% end %></td>
</tr><br>

<tr><td><%= @match.golfer1_name %> </td>
<% @match.course.holes.count.times do |l| %>
<td><select name="hole_score" id="" class="form-control" style="width: 40px;">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
	    <option value="10">10</option>
            <option value="max">M</option>
</select></td><% end %>
</tr>

<tr><td><%= @match.golfer2_name %></td>
<% @match.course.holes.count.times do |l| %>
<td><select name="hole_score" id="" class="form-control" style="width: 40px;">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
	    <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
	    <option value="10">10</option>
            <option value="max">M</option>
</select></td><% end %>
</tr>
</table>

<p />
<%= link_to 'Next', edit_match_path(@match), :class => 'btn btn-success btn-small' %> |
<%= link_to 'Back', matches_path %>
</section>
<footer></footer>
</body>
</html>